[2022-01-31 21:52:32,034] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Spotify_Song_dag.spotify_etl scheduled__2022-01-31T21:49:16.341989+00:00 [queued]>
[2022-01-31 21:52:32,045] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Spotify_Song_dag.spotify_etl scheduled__2022-01-31T21:49:16.341989+00:00 [queued]>
[2022-01-31 21:52:32,046] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 21:52:32,046] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-31 21:52:32,046] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-31 21:52:32,093] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): spotify_etl> on 2022-01-31 21:49:16.341989+00:00
[2022-01-31 21:52:32,099] {standard_task_runner.py:52} INFO - Started process 49597 to run task
[2022-01-31 21:52:32,106] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Spotify_Song_dag', 'spotify_etl', 'scheduled__2022-01-31T21:49:16.341989+00:00', '--job-id', '830', '--raw', '--subdir', 'DAGS_FOLDER/spotify_check_dag.py', '--cfg-path', '/var/folders/nx/v6d0bskn22s742wqx2vwc_rm0000gn/T/tmptcprzuw_', '--error-file', '/var/folders/nx/v6d0bskn22s742wqx2vwc_rm0000gn/T/tmpgwi8b315']
[2022-01-31 21:52:32,109] {standard_task_runner.py:77} INFO - Job 830: Subtask spotify_etl
[2022-01-31 21:52:32,181] {logging_mixin.py:109} INFO - Running <TaskInstance: Spotify_Song_dag.spotify_etl scheduled__2022-01-31T21:49:16.341989+00:00 [running]> on host Anurags-MacBook-Pro.local
[2022-01-31 21:52:32,246] {logging_mixin.py:109} WARNING - /Users/user/Youtubed/YTVM/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py:510 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2022-01-31 21:52:32,254] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Spotify_Song_dag
AIRFLOW_CTX_TASK_ID=spotify_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T21:49:16.341989+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-31T21:49:16.341989+00:00
[2022-01-31 21:52:32,342] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/Youtubed/dags/spotify_check_dag.py", line 47, in spotify_etl_function
    for song in data["items"]:
KeyError: 'items'
[2022-01-31 21:52:32,352] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=Spotify_Song_dag, task_id=spotify_etl, execution_date=20220131T214916, start_date=20220131T215232, end_date=20220131T215232
[2022-01-31 21:52:32,364] {standard_task_runner.py:89} ERROR - Failed to execute job 830 for task spotify_etl
Traceback (most recent call last):
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/user/Youtubed/dags/spotify_check_dag.py", line 47, in spotify_etl_function
    for song in data["items"]:
KeyError: 'items'
[2022-01-31 21:52:32,378] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-31 21:52:32,410] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-31 21:52:32,413] {logging_mixin.py:109} WARNING - /Users/user/Youtubed/YTVM/lib/python3.9/site-packages/airflow/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
